from enum import Enum

class PropertiesData(Enum):
    ALASKA = {"PROPERTIES": 1, "COMMINGSOON": 0}
    ARIZONA = {"PROPERTIES": 1, "COMMINGSOON": 0}
    CALIFORNIA = {"PROPERTIES": 22, "COMMINGSOON": 18}
    CHIHUAHUA = {"PROPERTIES": 0, "COMMINGSOON": 1}
    COLORADO = {"PROPERTIES": 7, "COMMINGSOON": 0}
    CONNECTICUT = {"PROPERTIES": 1, "COMMINGSOON": 0}
    FLORIDA = {"PROPERTIES": 7, "COMMINGSOON": 26}
    GEORGIA = {"PROPERTIES": 5, "COMMINGSOON": 0}
    HAWAII = {"PROPERTIES": 3, "COMMINGSOON": 0}
    IDAHO = {"PROPERTIES": 2, "COMMINGSOON": 0}
    MAINE = {"PROPERTIES": 1, "COMMINGSOON": 0}
    MASSACHUSETTS = {"PROPERTIES": 2, "COMMINGSOON": 0}
    MICHIGAN = {"PROPERTIES": 2, "COMMINGSOON": 0}
    MONTANA = {"PROPERTIES": 7, "COMMINGSOON": 0}
    NAYARIT = {"PROPERTIES": 15, "COMMINGSOON": 0}
    NEVADA = {"PROPERTIES": 0, "COMMINGSOON": 1}
    NEW_JERSEY = {"PROPERTIES": 1, "COMMINGSOON": 0}
    NEW_YORK = {"PROPERTIES": 6, "COMMINGSOON": 6}
    NORTH_CAROLINA = {"PROPERTIES": 5, "COMMINGSOON": 2}
    OREGON = {"PROPERTIES": 4, "COMMINGSOON": 0}
    QUINTANA_ROO = {"PROPERTIES": 0, "COMMINGSOON": 1}
    SOUTH_CAROLINA = {"PROPERTIES": 1, "COMMINGSOON": 0}
    ST_THOMAS = {"PROPERTIES": 1, "COMMINGSOON": 0}
    TENNESSEE = {"PROPERTIES": 2, "COMMINGSOON": 0}
    TEXAS = {"PROPERTIES": 5, "COMMINGSOON": 3}
    UTAH = {"PROPERTIES": 0, "COMMINGSOON": 2}
    VERMONT = {"PROPERTIES": 4, "COMMINGSOON": 1}
    VIRGINIA = {"PROPERTIES": 1, "COMMINGSOON": 0}
    WASHINGTON = {"PROPERTIES": 3, "COMMINGSOON": 1}
    WISCONSIN = {"PROPERTIES": 2, "COMMINGSOON": 0}
    WYOMING = {"PROPERTIES": 1, "COMMINGSOON": 0}
   